/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alipay_mobile_quinox_classloader_InitExecutor */
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#ifndef _Included_com_alipay_mobile_quinox_classloader_InitExecutor
#define _Included_com_alipay_mobile_quinox_classloader_InitExecutor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alipay_mobile_quinox_classloader_InitExecutor
 * Method:    dexopt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_alipay_mobile_quinox_classloader_InitExecutor_dexopt
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
