/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class blue_stack_openAtlas_dexopt_InitExecutor */
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include<sys/wait.h>
#include<utime.h>
#ifndef _Included_blue_stack_openAtlas_dexopt_InitExecutor
#define _Included_blue_stack_openAtlas_dexopt_InitExecutor
#ifdef __cplusplus

extern "C" {
#endif
/*
 * Class:     blue_stack_openAtlas_dexopt_InitExecutor
 * Method:    dexopt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_openAtlas_dexopt_InitExecutor_dexopt
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
